Add:

#cpr
INCDIR += -I/usr/local/include
LIBDIR += -L/usr/local/lib
LIBS += -lcpr

Find:
dev_log.cpp

Change:
dev_log.cpp discord.cpp

If you have cannot find -lcpr error:
remove -static flag(at CFLAGS)