#include "service.h"

#if defined(__BL_DISCORD_MESSAGE__)
enum EDiscordTokens
{
	DISCORD_TOKEN_ADMIN_MALI,
	DISCORD_TOKEN_GM_BLACK,
	DISCORD_TOKEN_BOT_TS,

	DISCORD_TOKEN_MAX,
};

enum EDiscordChannels
{
	DISCORD_CHANNEL_BLACK_GENERAL,
	DISCORD_CHANNEL_BLACK_ANNOUNCEMENTS,

	DISCORD_CHANNEL_MAX,
};
#endif